#167377493 Users should be able Signup/Register to 1kbIdeas
andela/vali-ah-frontend pull request #12
Opened 2019-08-30 14:28 UTC by Jonathan4github

### What does this PR do?
This PR implements a signup functionality frontend 
#### Description of Task to be completed
- Create a re-useable input textbox component
- Create signup actions and reducers
#### How should this be manually tested?
- Clone and cd into this repository
- run ```npm install```&```npm run start:dev```
- Navigate to http://localhost:{Port}/signup
- Then supply the user detail data and submit

#### Any Background Context You want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#167377493](https://pivotaltracker.com/story/show/167377493)

#### Screenshots (if appropriate)

#### Questions:

2019-09-04 22:04 UTC, iverenshaguy commented
I merged the conflicting PR since morning. I'm surprised it has not been rebased yet. Please what is going on?

2019-09-04 23:05 UTC, Jonathan4github commented
> I merged the conflicting PR since morning. I'm surprised it has not been rebased yet. Please what is going on?

I have rebased the branch.

2019-09-08 16:07 UTC, iverenshaguy commented
@successgilli Please review this PR and ensure that it adheres to our convention, thanks

2019-09-09 13:16 UTC, successgilli requested changes
Nice job so far @Jonathan4github.
Please, review my comments and reproduce them in all files affected.
Thanks

2019-09-09 13:16 UTC, successgilli commented on package.json
> +    "jest-mock": "^24.9.0",
Please, jest-mock is already integrated into jest.
You can uninstall this.

2019-09-09 13:16 UTC, successgilli commented on src/components/Signup/Signup.spec.jsx
> +import React from 'react';
Add the proper comments and import ordering. e.g // styles

2019-09-09 13:16 UTC, successgilli commented on src/components/Signup/index.jsx
> +              <input
Please, use the reusable input component in our project

2019-09-11 09:21 UTC, iverenshaguy commented
@Jonathan4github Please bump up the test coverage on this feature. It is too low

2019-09-11 09:21 UTC, iverenshaguy commented
Also, I can't see any e2e tests. Did you write any? If you didn't, please do that.

2019-09-11 12:00 UTC, successgilli requested changes
Some of the feedback I gave has not been implemented. Please, is there a reason for this ?

2019-09-11 12:00 UTC, successgilli commented on package.json
> +    "jest-mock": "^24.9.0",
@Jonathan4github , you have not yet removed jest-mock

2019-09-11 12:00 UTC, successgilli commented on src/components/Signup/Signup.spec.jsx
> +
Please, use proper import ordering.

2019-09-11 12:06 UTC, successgilli commented on src/utils/validator/index.js
> +export default class FormValidator {
Do you think we need jsdoc for this ?

2019-09-11 12:13 UTC, Jonathan4github reviewed
> Also, I can't see any e2e tests. Did you write any? If you didn't, please do that. Fill in the fields with invalid data, check that the correct errors are displayed, and then fill them with accurate data, check that no error is displayed. Do not click to submit the form though. This is because we do not want to keep signing up many users, we don't have the resource for this.

Okay I'm on that.

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.spec.jsx
> +import jest from 'jest-mock';
remove jest-mock

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.spec.jsx
> +    const message = 'message';
auth props change to success message

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.scss
> +    .label__inputElem {
remove camel case

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.scss
> +    .form__submitBtn {
remove camel case

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.scss
> +  .loader-div {
loader wrapper

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/Signup.scss
> +      color: #FFF;
all color code should be  in variables

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +    signup: PropTypes.string.isRequired
use shape instead of string

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +    signup: PropTypes.string.isRequired
change signin  and login to auth

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +  handleInput = (e) => {
change e to event

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +    const newFields = { ...fields, [name]: value };
change fields to ...others

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +    const validatorErrors = new Validation(signupValidation.Signup).validate(newFields);
export the signup

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +    e.preventDefault();
change e to event

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +      'info-msg': success,
remove 113

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +        <form className="form" onSubmit={this.handleSubmit}>
change form to signup class

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +          <div className="section">
change the section classs to another name

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +                onChange={this.handleInput}
Capitalize placeholder

2019-09-11 12:13 UTC, Jonathan4github commented on src/components/Signup/index.jsx
> +              (isRequesting === true) && <div className="loader-div"><div className="loader" /></div>
isRequesting
!isRequesting

fix to one line

2019-09-11 12:13 UTC, Jonathan4github commented on src/store/modules/signUp/index.js
> +export const createUserRequest = (bool) => ({ type: CREATE_USER_REQUEST, payload: bool });
```suggestion
export const createUserRequest = () => ({ type: CREATE_USER_REQUEST});
```

2019-09-11 12:13 UTC, Jonathan4github commented on src/store/modules/signUp/index.js
> +export function* getSignupRequestSaga({ payload }) {
getSignupRequestSaga to getSignupRequest

2019-09-11 12:13 UTC, Jonathan4github commented on src/store/modules/signUp/signup.reducers.test.js
> +  getSignupRequestSaga
getSignupRequestSaga to getSignupRequest

2019-09-11 12:13 UTC, Jonathan4github commented on src/validations/Signup.js
> +  Signup: (validator) => [
export default it

2019-09-12 09:26 UTC, successgilli commented on src/store/modules/signUp/index.js
> +export const createUserRequest = (bool) => ({ type: CREATE_USER_REQUEST, payload: bool });
This has not been updated

2019-09-12 10:22 UTC, successgilli approved these changes
Good job @Jonathan4github implementing all feedback.

2019-09-12 10:24 UTC, iverenshaguy approved these changes

2019-09-12 10:24 UTC, merged