#167377496 Create user signin form and popup modal
andela/vali-ah-frontend pull request #14
Opened 2019-08-30 14:52 UTC by successgilli

#### What does this PR do?
This pull request provides the user with an interactive modal for login
#### Description of Task to be completed
- create user signin modal
- authenticate login details
#### How should this be manually tested?
N/A
#### Any Background Context You want to provide?
N/A
#### What are the relevant pivotal tracker stories?

[#167377496](https://pivotaltracker.com/story/show/167377496)

#### Screenshots (if appropriate)

#### Questions:
N/A

2019-09-04 21:31 UTC, iverenshaguy commented
Hi Gilbert, good job here. Please, break up your storybook stories into components i.e input box, button (replace the former one), base modal (not the signup modal but what the base modal component looks like) etc. Let our storybook stories be for components and not pages or full features (e.g . signin). Thanks

2019-09-04 22:00 UTC, iverenshaguy requested changes
Review 1.0

Please review and I remember saying we should all read the team convention and ensure we adhere to it. This PR doesn't show me that this has been done. I will continue my review once you implement the other ones

2019-09-04 22:00 UTC, iverenshaguy commented on .eslintrc
> +    "import/no-named-as-default": 0,
Why was this rule added?

2019-09-04 22:00 UTC, iverenshaguy commented on package.json
> +    "qs": "^6.8.0",
Why? Can we not create our own util?

2019-09-04 22:00 UTC, iverenshaguy commented on package.json
> +    "isomorphic-fetch": "^2.2.1",
We are already using Axios, please why do we have this?

2019-09-04 22:00 UTC, iverenshaguy commented on package.json
> +    "jest-mock": "^24.9.0",
Jest-mock? I fail to see the usefulness of this package

2019-09-04 22:00 UTC, iverenshaguy commented on package.json
> +    "jest-mock": "^24.9.0",
I think Jest has an in-built mocking functionality. Or has this been separated into Jest-mock?

2019-09-04 22:00 UTC, iverenshaguy commented on src/App/index.jsx
> +// import Header from 'components/Header';
What's going on in this file. Please fix and try to pay more attention to details.

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.scss
> +body {
Please create a reusable Modal component that the Signin/Signup and all other modals will extend.

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.spec.jsx
> +import { Modal } from './index';
This base modal will not be connected to anything. It will simply be a normal React component. You'll have to break this test into the normal modal and then the Signin/Signup/Welcome modal

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.spec.jsx
> +  it('should toggle and display the signin component on clicking singin', () => {
```suggestion
  it('should toggle and display the signin component on signin link click', () => {
```

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.spec.jsx
> +    const wrapper = shallow(<Modal formType={false} show />);
formType={false}? How is formType a boolean variable? Please correct

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.stories.jsx
> +// third-party libraries
```suggestion

// third-party libraries
```

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.stories.jsx
> +// import { action } from '@storybook/addon-actions';
We shouldn't have commented out code in a PR that is ready for review. Please remove it

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/Modal.stories.jsx
> +    <Provider store={store}>
I do not want to see any connected component in our stories. Please export the main component and use it here

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +import './Modal.scss';
Your import ordering is wrong and your imports don't have the correct heading e.g `// react libraries`. It might seem like a silly convention but it is also helping to assess how you guys pay attention to details and follow the team conventions, even silly ones. Also, the style import should always be the last thing.

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +    formType: PropTypes.bool.isRequired,
This is unacceptable ie. formType as a boolean prop. What if it needs to be extended for Forgot Password, true or false seems like a really weird value to pass to the form for this use case. Please, rewrite the Modal component and then create a Signin/Signup Modal component that renders this base Modal component with the correct view.

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +    this.setState({ signin: !signin });
??? I'm not comfortable with the whole flow for this component. Please refactor it. You can check different apps get ideas

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +                <p className="modal__text">Sign into your account to serve you more personalised stories from creatives</p>
Sign in still? I thought this was supposed to be rendering the sign up modal

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +              <div className="modal__left">
Please break out the code on line 61 - 72 into a class method ie. renderModalText() {} or soemthing like that. It will render the correct one based on the formType prop

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +            <div className="modal__authComponent">
```suggestion
            <div className="modal__auth-component">
```
We will not have camel-cased class names. This is why BEM uses `__ `and `--`, so that you can have `_` and `-` for classnames. Kindly correct

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +                { signin
Please re-read our Wiki very well and ensure you are sticking to the conventions concerning JSX structure. I can hardly read this code. Please restructure

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/Signin.spec.jsx
> +  it('initial state of inputs should be an empty string', () => {
??? ```it initial state of inputs should be an empty string```. Please restructure your test heading and assume it starts with "it"

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/Signin.stories.jsx
> +// react libraries
Same feedback as above

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/Signins.scss
> +@import url('https://fonts.googleapis.com/css?family=Rubik:400,700&display=swap');
Signins?

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/Signins.scss
> +.loginForm {
```suggestion
.login-form {
```

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/index.jsx
> +import React from 'react';
Rearrange and label this according to the import ordering document

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/index.jsx
> +    // eslint-disable-next-line react/forbid-prop-types
Why was this disabled?

2019-09-04 22:00 UTC, iverenshaguy commented on src/components/Signin/index.jsx
> +    login: PropTypes.object.isRequired,
Why are you using PropTypes.object.isRequired and not PropTypes.shape({...})?

2019-09-04 22:02 UTC, iverenshaguy commented
I can't see the button that triggers the modal (we talked about this during your live review). I can't see that in your implementation and therefore can't test it or merge.

2019-09-04 22:03 UTC, iverenshaguy commented
Please fix Code climate issues

2019-09-05 14:41 UTC, successgilli commented on .eslintrc
> +    "import/no-named-as-default": 0,
I was having issues with imports of my components so I installed that but I discovered a way to fix it.
I already uninstalled it.

2019-09-05 14:42 UTC, successgilli commented on package.json
> +    "qs": "^6.8.0",
I uninstalled it.
I was trying to stringify Axios arguments before sending requests.

2019-09-05 14:42 UTC, successgilli commented on package.json
> +    "isomorphic-fetch": "^2.2.1",
I was using this before the team agreed on Axios so I had to switch.
I uninstalled it.

2019-09-05 14:43 UTC, successgilli commented on package.json
> +    "jest-mock": "^24.9.0",
jest now support jest-mock by default.
I uninstalled it.

2019-09-05 14:43 UTC, successgilli commented on src/App/index.jsx
> +// import Header from 'components/Header';
I removed it.

2019-09-05 14:45 UTC, successgilli commented on src/components/Signin/Signins.scss
> +@import url('https://fonts.googleapis.com/css?family=Rubik:400,700&display=swap');
This is an issue with netlify same as @Merkll had.
It took an initial state of my files and references them even when I changed their name.
I will still work on that.

2019-09-05 14:46 UTC, successgilli commented on src/components/Signin/Signins.scss
> +.loginForm {
This is a better name convention.
I agree. Thanks

2019-09-05 14:46 UTC, successgilli commented on src/components/Signin/index.jsx
> +import React from 'react';
yes...order must be maintained

2019-09-05 14:47 UTC, successgilli commented on src/components/Signin/index.jsx
> +    // eslint-disable-next-line react/forbid-prop-types
It was the only way I knew how to name an object proptype.
I didn't know there was another way.
I removed the disabling statement.

2019-09-05 14:48 UTC, successgilli commented on src/components/Signin/index.jsx
> +    login: PropTypes.object.isRequired,
Same as above.
Thanks for the information.

2019-09-05 14:49 UTC, successgilli commented
> Hi Gilbert, good job here. Please, break up your storybook stories into components i.e input box, button (replace the former one), base modal (not the signup modal but what the base modal component looks like) etc. Let our storybook stories be for components and not pages or full features (e.g . signin). Thanks



> I can't see the button that triggers the modal (we talked about this during your live review). I can't see that in your implementation and therefore can't test it or merge.

The button is to be done by @kennyedward on the landing page where when clicked, a prop is passed to y component to show the auth modal containing signup and signin.

2019-09-05 15:13 UTC, successgilli commented on src/components/Modal/Modal.scss
> +body {
> Please create a reusable Modal component that the Signin/Signup and all other modals will extend.

Okay, I will attempt that

2019-09-05 15:13 UTC, successgilli commented on src/components/Modal/index.jsx
> +    formType: PropTypes.bool.isRequired,
I built the modal according to the mockup.
I will work on that.

2019-09-05 15:13 UTC, successgilli commented on src/components/Modal/index.jsx
> +                <p className="modal__text">Sign into your account to serve you more personalised stories from creatives</p>
No, it toggles between signin and signup.
According to the mockup.
There is no specific modal for signin and signup.
Just auth modal according to the mockup.

2019-09-05 17:36 UTC, iverenshaguy commented on src/components/Modal/index.jsx
> +                <p className="modal__text">Sign into your account to serve you more personalised stories from creatives</p>
Yeah but do we still have the same wording on the both of them?

2019-09-06 06:50 UTC, successgilli commented on src/components/Modal/index.jsx
> +                <p className="modal__text">Sign into your account to serve you more personalised stories from creatives</p>
No we dont

2019-09-08 15:16 UTC, iverenshaguy approved these changes

2019-09-08 15:16 UTC, merged