#168105120 Landing page
andela/vali-ah-frontend pull request #16
Opened 2019-08-30 20:14 UTC by kennyedward

#### What does this PR do?
This pull request creates a landing page for users

#### Description of Task to be completed
- creates user's landing page

#### How should this be manually tested?
N/A

#### Any Background Context You want to provide?
N/A
#### What are the relevant pivotal tracker stories?

[#168105120](https://pivotaltracker.com/story/show/168105120)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-09-05 14:49 UTC, kennyedward commented on src/store/index.js
> +// store.dispatch({ type: 'GET_CATEGORY', payload: { query: 'emotion' } });
remove commented code

2019-09-06 08:21 UTC, iverenshaguy approved these changes

2019-09-06 08:21 UTC, iverenshaguy commented
LGTM. I would not want us to use camelCased class names though. So please adjust this

2019-09-06 08:28 UTC, iverenshaguy commented
Do I merge then you implement my feedback later? Feedback:
- The navbar is not properly aligned to the top and side of the page. 
- This back to top button should slide the page slowly not as quickly as we have in our current implementation. 
- The card content should determine the size of the card. Right now, all our cards are the same size. The PO doesn't want this. 
- The selection modal should show a loader when the user clicks on her category interset so that she has feedback that something is happening and is not wondering why her page isn't loading. 
- Reloading the page shouldn't bring out the modal again, the selected category should be stored for further use. You can use any of the available browser storages.
- I didn't get any results when I selected the first category in the modal, there should be a fallback set of stories to be rendered whenever the selected category returns no result so that we don't confuse the user

2019-09-06 08:50 UTC, iverenshaguy requested changes
Would just request changes since we don't need to merge now

2019-09-09 09:58 UTC, kennyedward commented on package.json
> +    "favicons-webpack-plugin": "^1.0.1",
Place in dev dependencies

2019-09-09 10:01 UTC, kennyedward commented on package.json
> +    "semantic-ui-css": "^2.4.1",
Place this under dependencies.

2019-09-09 10:05 UTC, kennyedward commented on src/assets/scss/style.scss
> +.show {
Create a loader component that renders the framework's loader and overrides its styles.

2019-09-09 10:12 UTC, kennyedward commented on src/components/ArticleCard/index.jsx
> +    <div className="card-wrapper__card">
```suggestion
    <div className="card">
```

2019-09-12 18:17 UTC, merged